;;;; Generated by TyCL transpiler
;;;; DO NOT EDIT - changes will be overwritten

(in-package #:cl-user)

(defun add (x y) "Add two integers" (+ x y))

(defun greet (name) "Greet a person by name" (format nil "Hello, ~A!" name))

(defun process-value (value)
  "Process a value that can be either integer or string"
  (etypecase value
    (integer (format nil "Number: ~D" value))
    (string (format nil "String: ~A" value))))

(defun get-names () "Return a list of strings" '("Alice" "Bob" "Charlie"))

(defun sum-list (numbers)
  "Sum a list of integers"
  (reduce #'+ numbers :initial-value 0))

(defun make-cache ()
  "Create a hash table mapping strings to integers"
  (let ((cache (make-hash-table :test 'equal)))
    (setf (gethash "one" cache) 1)
    (setf (gethash "two" cache) 2)
    cache))

(defvar *config* (make-hash-table :test 'equal) "Global configuration")

(defparameter *max-count* 100 "Maximum count")

(defconstant +pi+ 3.14159d0 "Pi constant")

(defclass person nil
          ((name :initarg :name :accessor person-name :documentation
            "Person's name")
           (age :initarg :age :accessor person-age :documentation
            "Person's age")
           (email :initarg :email :initform "" :accessor person-email
            :documentation "Person's email")))

(defclass employee (person)
          ((employee-id :initarg :employee-id :accessor employee-id)
           (salary :initarg :salary :accessor employee-salary)))

(defmethod display (p)
  "Display person information"
  (format nil "~A (~D)" (person-name p) (person-age p)))

(defmethod display (e)
  "Display employee information"
  (format nil "Employee ~A: ~A (~D)" (employee-id e) (person-name e)
          (person-age e)))

(defun test-local ()
  "Test local variable types"
  (let ((x 10) (y "hello") (z 20))
    (format t "x=~A y=~A z=~A~%" x y z)))

(defun nested-data () "Return nested list structure" '((1 2 3) (4 5 6) (7 8 9)))

(defun complex-map ()
  "Return hash table with list values"
  (let ((map (make-hash-table :test 'equal)))
    (setf (gethash "primes" map) '(2 3 5 7 11))
    (setf (gethash "evens" map) '(2 4 6 8 10))
    map))

