;;;; TyCL Transpiler
;;;; Converts .tycl files to .lisp files by stripping type annotations

(in-package #:tycl/transpiler)

(defun transpile-form (form &key extract-types)
  "Convert a single form from TyCL to CL by stripping type annotations.
   Recursively processes lists and returns atoms as-is.
   If EXTRACT-TYPES is T, also extracts type information."
  (when extract-types
    (tycl:extract-type-from-form form))
  
  (cond
    ;; Type annotation - extract symbol only
    ((type-annotation-p form)
     (annotation-symbol form))
    
    ;; List - recursively process each element
    ((consp form)
     (cons (transpile-form (car form))
           (transpile-form (cdr form))))
    
    ;; Atom - return as-is
    (t form)))

(defun transpile-string (tycl-string &key extract-types)
  "Transpile TyCL source code string to CL source code string.
   Returns the transpiled code as a string.
   If EXTRACT-TYPES is T, also extracts type information.
   Uses 2-pass approach: read all forms, extract types + type check, then transpile."
  (let ((*readtable* *tycl-readtable*)
        (raw-forms nil))
    ;; Pass 1: Read all forms
    (with-input-from-string (in tycl-string)
      (loop for form = (read in nil :eof)
            until (eq form :eof)
            do (push form raw-forms)))
    (setf raw-forms (nreverse raw-forms))
    ;; Pass 2: Extract type information (before transpilation strips annotations)
    (when extract-types
      (dolist (form raw-forms)
        (tycl:extract-type-from-form form)))
    ;; Pass 2.5: Type checking (if enabled)
    (when tycl/type-checker:*enable-type-checking*
      (let ((tycl/type-checker:*type-check-errors* nil))
        (tycl/type-checker:run-type-checks raw-forms)
        (when tycl/type-checker:*type-check-errors*
          (let ((errors (reverse tycl/type-checker:*type-check-errors*)))
            ;; Always warn
            (dolist (err errors)
              (warn "Type error: ~A (in ~S)"
                    (tycl/type-checker:error-message err)
                    (tycl/type-checker:error-form err)))
            ;; Signal error if :error mode
            (when (eq tycl/type-checker:*enable-type-checking* :error)
              (error "Type checking failed with ~D error~:P"
                     (length errors)))))))
    ;; Pass 3: Transpile each form
    (with-output-to-string (out)
      (format out ";;;; Generated by TyCL transpiler~%")
      (format out ";;;; DO NOT EDIT - changes will be overwritten~%~%")
      (dolist (form raw-forms)
        (let ((transpiled (transpile-form form)))
          (write transpiled :stream out :pretty t :case :downcase)
          (terpri out)
          (terpri out))))))

(defun transpile-file (input-file &optional output-file &key extract-types save-types)
  "Transpile a .tycl file to a .lisp file.
   If OUTPUT-FILE is not specified, uses INPUT-FILE with .lisp extension.
   If EXTRACT-TYPES is T, extracts type information during transpilation.
   If SAVE-TYPES is T, saves type information to .tycl-types file.
   Returns the output file path."
  (let* ((output (or output-file
                     (make-pathname :type "lisp"
                                    :defaults input-file)))
         (tycl:*current-file* (namestring input-file))
         (tycl:*current-package* "COMMON-LISP-USER"))
    ;; Load hook configuration if exists
    (when extract-types
      (tycl:find-and-load-hooks (uiop:pathname-directory-pathname input-file)))
    
    ;; Transpile
    (let* ((tycl-source (uiop:read-file-string input-file))
           (cl-source (transpile-string tycl-source :extract-types extract-types)))
      (ensure-directories-exist output)
      (with-open-file (out output
                           :direction :output
                           :if-exists :supersede
                           :if-does-not-exist :create)
        (write-string cl-source out))
      (format t "~&Transpiled: ~A -> ~A~%" input-file output)
      
      ;; Save type information if requested (project-level tycl-types.tmp in cwd)
      (when (and extract-types save-types)
        (tycl:save-project-types
         (make-pathname :name "tycl-types" :type "tmp"
                        :defaults *default-pathname-defaults*)))
      
      output)))
