;;;; TyCL Transpiler
;;;; Converts .tycl files to .lisp files by stripping type annotations

(in-package #:tycl/transpiler)

(defun transpile-form (form &key extract-types)
  "Convert a single form from TyCL to CL by stripping type annotations.
   Recursively processes lists and returns atoms as-is.
   If EXTRACT-TYPES is T, also extracts type information."
  (when extract-types
    (tycl:extract-type-from-form form))
  
  (cond
    ;; Type annotation - extract symbol only
    ((type-annotation-p form)
     (annotation-symbol form))
    
    ;; List - recursively process each element
    ((consp form)
     (cons (transpile-form (car form))
           (transpile-form (cdr form))))
    
    ;; Atom - return as-is
    (t form)))

(defun transpile-string (tycl-string &key extract-types)
  "Transpile TyCL source code string to CL source code string.
   Returns the transpiled code as a string.
   If EXTRACT-TYPES is T, also extracts type information."
  (let ((*readtable* *tycl-readtable*)
        (forms nil))
    ;; Read all forms from the string
    (with-input-from-string (in tycl-string)
      (loop for form = (read in nil :eof)
            until (eq form :eof)
            do (push (transpile-form form :extract-types extract-types) forms)))
    ;; Convert back to string
    (with-output-to-string (out)
      (format out ";;;; Generated by TyCL transpiler~%")
      (format out ";;;; DO NOT EDIT - changes will be overwritten~%~%")
      (dolist (form (nreverse forms))
        (write form :stream out :pretty t :case :downcase)
        (terpri out)
        (terpri out)))))

(defun transpile-file (input-file &optional output-file &key extract-types save-types)
  "Transpile a .tycl file to a .lisp file.
   If OUTPUT-FILE is not specified, uses INPUT-FILE with .lisp extension.
   If EXTRACT-TYPES is T, extracts type information during transpilation.
   If SAVE-TYPES is T, saves type information to .tycl-types file.
   Returns the output file path."
  (let* ((output (or output-file
                     (make-pathname :type "lisp"
                                    :defaults input-file)))
         (tycl:*current-file* (namestring input-file))
         (tycl:*current-package* "COMMON-LISP-USER"))
    ;; Load hook configuration if exists
    (when extract-types
      (tycl:find-and-load-hooks (uiop:pathname-directory-pathname input-file)))
    
    ;; Transpile
    (let* ((tycl-source (uiop:read-file-string input-file))
           (cl-source (transpile-string tycl-source :extract-types extract-types)))
      (ensure-directories-exist output)
      (with-open-file (out output
                           :direction :output
                           :if-exists :supersede
                           :if-does-not-exist :create)
        (write-string cl-source out))
      (format t "~&Transpiled: ~A -> ~A~%" input-file output)
      
      ;; Save type information if requested
      (when (and extract-types save-types)
        (tycl:save-package-types tycl:*current-package* input-file))
      
      output)))
