;;;; Type Information Serialization
;;;; Serializes type database to tycl-types.tmp project files

(in-package #:tycl)

;;; S-expression Serialization

(defun serialize-type-info (type-info)
  "Convert type-info object to S-expression"
  (etypecase type-info
    (value-type-info
     `(:value
       :symbol ,(type-info-symbol type-info)
       :type ,(value-type-spec type-info)))
    (function-type-info
     `(:function
       :symbol ,(type-info-symbol type-info)
       :params ,(function-params type-info)
       :return ,(function-return-type type-info)))
    (method-type-info
     `(:method
       :symbol ,(type-info-symbol type-info)
       :params ,(function-params type-info)
       :return ,(function-return-type type-info)
       :specializers ,(method-specializers type-info)))
    (class-type-info
     `(:class
       :symbol ,(type-info-symbol type-info)
       :slots ,(class-slots type-info)
       :superclasses ,(class-superclasses type-info)))))

(defun serialize-package-types (package)
  "Serialize all type information for a package"
  (let ((symbols (get-package-symbols package))
        (entries nil))
    (dolist (symbol symbols)
      (let ((type-info (lookup-type-info package symbol)))
        (when type-info
          (push (serialize-type-info type-info) entries))))
    (nreverse entries)))

(defun serialize-type-database (package)
  "Serialize type database for a package to S-expression"
  `(:tycl-type-database
    :version ,(db-version *type-database*)
    :package ,package
    :timestamp ,(format-timestamp (db-timestamp *type-database*))
    :entries ,(serialize-package-types package)))

(defun format-timestamp (universal-time)
  "Format universal time to ISO 8601 string"
  (multiple-value-bind (sec min hour day month year)
      (decode-universal-time universal-time)
    (format nil "~4,'0D-~2,'0D-~2,'0DT~2,'0D:~2,'0D:~2,'0DZ"
            year month day hour min sec)))

;;; Project-level functions

(defun get-all-known-packages ()
  "Get all package names that have registered type information"
  (let ((packages nil))
    (maphash (lambda (package symbols)
               (declare (ignore symbols))
               (push package packages))
             (db-package-index *type-database*))
    (nreverse packages)))

(defun generate-project-type-file-path (asd-path)
  "Generate tycl-types.tmp path in the same directory as the .asd file"
  (make-pathname :name "tycl-types"
                 :type "tmp"
                 :defaults (uiop:pathname-directory-pathname asd-path)))

;;; File I/O

(defun write-type-database (package output-file)
  "Write type database for a package to a file (single package)"
  (with-open-file (out output-file
                       :direction :output
                       :if-exists :supersede
                       :if-does-not-exist :create)
    (format out ";;;; TyCL Type Database~%")
    (format out ";;;; Package: ~A~%" package)
    (format out ";;;; Generated: ~A~%" (format-timestamp (get-universal-time)))
    (format out ";;;; DO NOT EDIT - Auto-generated by TyCL transpiler~%~%")
    (let ((*print-case* :downcase))
      (pprint (serialize-type-database package) out))
    (terpri out))
  output-file)

(defun write-project-type-database (output-file)
  "Write all packages' type information to a single project file"
  (let ((packages (get-all-known-packages)))
    (with-open-file (out output-file
                         :direction :output
                         :if-exists :supersede
                         :if-does-not-exist :create)
      (format out ";;;; TyCL Project Type Database~%")
      (format out ";;;; Generated: ~A~%" (format-timestamp (get-universal-time)))
      (format out ";;;; DO NOT EDIT - Auto-generated by TyCL transpiler~%~%")
      (let ((*print-case* :downcase))
        (dolist (package packages)
          (pprint (serialize-type-database package) out)
          (terpri out)
          (terpri out)))))
  output-file)

(defun save-project-types (output-file)
  "Save project type information, merging with existing file if present.
   Reads existing file first, then overwrites with merged data."
  (when (probe-file output-file)
    (handler-case
        (load-type-database output-file)
      (error (e)
        (warn "Failed to load existing type database from ~A: ~A" output-file e))))
  (write-project-type-database output-file)
  (format t "~&; Project type information saved to ~A~%" output-file)
  output-file)

;;; Deserialization

(defun deserialize-type-info (package sexp)
  "Convert S-expression to type-info object"
  (let ((kind (first sexp))
        (props (rest sexp)))
    (case kind
      (:value
       (make-value-type-info
        package
        (getf props :symbol)
        (getf props :type)))
      (:function
       (make-function-type-info
        package
        (getf props :symbol)
        (getf props :params)
        (getf props :return)))
      (:method
       (make-method-type-info
        package
        (getf props :symbol)
        (getf props :params)
        (getf props :return)
        (getf props :specializers)))
      (:class
       (make-class-type-info
        package
        (getf props :symbol)
        (getf props :slots)
        (getf props :superclasses)))
      (otherwise
       (warn "Unknown type info kind: ~A" kind)
       nil))))

(defun load-type-database (type-file)
  "Load type database from a project type file (supports multiple S-expressions)"
  (when (probe-file type-file)
    (with-open-file (in type-file :direction :input)
      (loop for data = (read in nil nil)
            while data
            do (progn
                 (unless (eq (first data) :tycl-type-database)
                   (error "Invalid type database file: ~A" type-file))
                 (let ((version (getf (rest data) :version))
                       (package (getf (rest data) :package))
                       (entries (getf (rest data) :entries)))
                   (when (> version (db-version *type-database*))
                     (warn "Type database version ~A is newer than supported version ~A"
                           version (db-version *type-database*)))
                   (dolist (entry entries)
                     (deserialize-type-info package entry)))))
      (format t "~&; Loaded type information from ~A~%" type-file)
      t)))
